spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    open-in-view: true
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: UTC
server:
  port: 8111
  context-path: /sign-center